# Generated by Django 5.1.5 on 2025-02-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=25, verbose_name='Номер телефона'),
        ),
    ]
