# Generated by Django 5.1.5 on 2025-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact_method',
            field=models.CharField(choices=[('call', 'Перезвонить'), ('whatsapp', 'Написать в WhatsApp'), ('tg', 'Написать в Telegram')], max_length=20, verbose_name='Способ обращения'),
        ),
    ]
