# Generated by Django 5.1.5 on 2025-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('auction_end_date', models.DateField(verbose_name='Дата завершения аукциона')),
                ('body_type', models.CharField(max_length=100, verbose_name='Тип кузова')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('transmission', models.CharField(max_length=100, verbose_name='Трансмиссия')),
                ('drivetrain', models.CharField(max_length=100, verbose_name='Привод')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='Номер кузова')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('import_type', models.CharField(max_length=100, verbose_name='Тип ввоза')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Итоговая стоимость')),
                ('main_image', models.ImageField(upload_to='cars/', verbose_name='Главное фото')),
                ('auction_sheet', models.ImageField(upload_to='auction_sheets/', verbose_name='Аукционный лист')),
            ],
        ),
    ]
