# Generated by Django 5.1.5 on 2025-02-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='main_image',
        ),
        migrations.AddField(
            model_name='car',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='car',
            name='auction_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения аукциона'),
        ),
        migrations.AlterField(
            model_name='car',
            name='auction_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='auction_sheets/', verbose_name='Аукционный лист'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='import_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип ввоза'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Трансмиссия'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/', verbose_name='Фото автомобиля')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.car', verbose_name='Автомобиль')),
            ],
        ),
    ]
