# Generated by Django 5.1.5 on 2025-02-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bodytype_brand_drivetrain_rating_alter_car_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.rating', verbose_name='Оценка'),
        ),
    ]
