# Generated by Django 5.1.5 on 2025-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_car_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_cc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем двигателя (cc)'),
        ),
    ]
