# Generated by Django 5.1.5 on 2025-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_car_engine_car_engine_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='origin',
            field=models.CharField(blank=True, choices=[('JP', 'Япония'), ('CN', 'Китай'), ('KR', 'Корея')], max_length=2, null=True, verbose_name='Страна происхождения'),
        ),
    ]
