# Generated by Django 5.1.5 on 2025-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='import_country',
            field=models.CharField(choices=[('JP', 'Япония'), ('CN', 'Китай'), ('KR', 'Корея')], default='JP', max_length=2, verbose_name='Страна ввоза'),
        ),
    ]
